services:

  pedidosapp:
    container_name: pedidos
    build:
      context: .
      dockerfile: project/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=dbPedidos
    depends_on:
      - dbPedidos

  dbPedidos:
    container_name: dbPedidos
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
